name: CIFAR-10 Image Classification CI/CD

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Jupyter Notebook
      run: |
        pip install nbconvert
        jupyter nbconvert --execute --to notebook --inplace Untitled.ipynb
